# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Path to your oh-my-zsh installation.
export ZSH="/Users/marceloaguiar/.oh-my-zsh"

# Kitty config files
export KITTY_CONFIG_DIRECTORY="$HOME/config/kitty"

# Brew
export PATH="/opt/homebrew/bin:$PATH"

# Bazel tools
export PATH=$PATH:$HOME/bin

# Go bin
export PATH=$PATH:$HOME/go/bin

# Python poetry
export PATH="/Users/marceloaguiar/.local/bin:$PATH"

# Rancher desktop (Docker)
export PATH="$HOME/.rd/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Java (make it first in path to skip MacOS default version)
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/azul-zulu/zulu-17.jdk/Contents/Home"

# RBENV =======================================
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# PyEnv setup
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Setup Bazel
export PATH="$PATH:$HOME/bin"
